### ISSUE TITLE
libusbx errors on OS X 10.8.4

### ISSUE THREAD

**Issue by Southern** [Benjamin-Dobell/Heimdall#130]
I get the following when trying to flash the SPH-L720 (Sprint S4):

```
Heimdall v1.4.0

Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
libusbx: error [submit_control_transfer] control request failed: no async port has been opened for interface
libusbx: error [submit_control_transfer] control request failed: no async port has been opened for interface

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 0100
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 82
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 01
           max packet size: 0200
          polling interval: 00
Claiming interface...
libusbx: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
ERROR: Claiming interface failed!
```

Nothing else is using the device at this point that I know of.

**Comment by alexander-yun** [comment]
Hi there. 
Hi, I have picture Phone (yellow triangle with "!" )  Computer at start of my device GT-P1000. It doesn't change if I press on power+vol- .
I tried follow this  article http://blog.giuseppeurso.net/how-i-fixed-my-galaxy-tab-7-aka-gt-p1000/ to resolve problem with bricked gt-p1000 (samsung galaxy tab 7") 

and get an error on the step 
$sudo heimdall flash --repartition --CACHE cache.rfs --DBDATAFS dbdata.rfs --FACTORYFS factoryfs.rfs --pit gt-p1000_mr.pit  --IBL+PBL boot.bin --MODEM modem.bin --PARAM param.lfs --SBL Sbl.bin --SBL2 Sbl.bin --KERNEL zImage --RECOVERY zImage --HIDDEN hidden.rfs --MOVINAND movinand.mst --verbose

...
libusbx: error [darwin_claim_interface] USBInterfaceOpen: another process has device opened for exclusive access
ERROR: Claiming interface failed!

I googled this error and found this page where people recomend unload Samsung kext
But I have not any kext here. 

kextstat | grep -v apple
Index Refs Address            Size       Wired      Name (Version) <Linked Against>
   61    0 0xffffff7f80d29000 0x48000    0x48000    at.obdev.nke.LittleSnitch (4246) <5 4 3 1>
  114    0 0xffffff7f80e0a000 0x5000     0x5000     com.driver.LogJoystick (2.0) <33 5 4 3>
  140    3 0xffffff7f8317b000 0x58000    0x58000    org.virtualbox.kext.VBoxDrv (4.3.28) <7 5 4 3 1>
  142    0 0xffffff7f831d3000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (4.3.28) <140 103 39 7 5 4 3 1>
  143    0 0xffffff7f831db000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (4.3.28) <140 7 5 4 3 1>
  144    0 0xffffff7f831e0000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (4.3.28) <140 5 4 1>
  145    0 0xffffff7f831e6000 0xd000     0xd000     com.eset.kext.esets_pfw (600.01.40f01) <4 3 1>
  146    0 0xffffff7f831f3000 0x15000    0x15000    com.eset.kext.esets_kac (600.01.40f01) <5 4 3 1>

So I have no idea what to do. Can you give me direction how to resolve this error?
