### ISSUE TITLE
Samung galaxy S II (i9100) ERROR: Failed to receive handshake response. Retrying...

### ISSUE THREAD

**Issue by gijzelaerr** [Benjamin-Dobell/Heimdall#156]
I somehow can't get heimdall 1.4 to work with Windows and Linux with my Samsung Galaxy SII (i9100). For linux (ubuntu, 13.04, 64bit) I tried the deb packages but also tried to compile the git master checkout from source. I've rebooted my machine after installation to enable the udev rules.

Complete log (including usb debug) for the master branch build: http://pastebin.com/eL9PaWpS

**Comment by Benjamin-Dobell** [comment]
Very old report. I'm assuming this is resolved on master (particularly since I own and have test on an I9100).
