### ISSUE TITLE
heimdall make failed.

### ISSUE THREAD

**Issue by FrankWestlake** [Benjamin-Dobell/Heimdall#172]
Platform: Linux Slackware 14.1
Hardware: HP Pavilion dm1 laptop
Device: Samsung Galaxy Note 3 (Verizon)

Make failed in heimdall because libusb.h was not included from 'heimdall/source/BridgeManager.cpp'. I changed #include <libusb.h> (line 25) to #include "../../libusbx-1.0/include/libusb.h" and the make succeeded.

After adding the error output to the bottom of this message I see that the error is in the make file: 'libusb-1.0' instead of 'libusbx-1.0'.

Successfully downloaded the PIT from a Samsung Galaxy Note 3 (Verizon).
ERROR OUTPUT:
/home/frank/Downloads/Heimdall-master/heimdall:# make
make  all-am
make[1]: Entering directory `/home/frank/Downloads/Heimdall-master/heimdall'
depbase=`echo source/BridgeManager.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -I/usr/include/libusb-1.0   -std=c++0x -I../libpit/Source   -g -O2 -MT source/BridgeManager.o -MD -MP -MF $depbase.Tpo -c -o source/BridgeManager.o source/BridgeManager.cpp &&\
mv -f $depbase.Tpo $depbase.Po
source/BridgeManager.cpp: In member function 'bool Heimdall::BridgeManager::DetectDevice()':
source/BridgeManager.cpp:503:36: error: 'LIBUSB_LOG_LEVEL_NONE' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_NONE);
                                    ^
source/BridgeManager.cpp:507:36: error: 'LIBUSB_LOG_LEVEL_ERROR' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_ERROR);
                                    ^
source/BridgeManager.cpp:511:36: error: 'LIBUSB_LOG_LEVEL_WARNING' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_WARNING);
                                    ^
source/BridgeManager.cpp:515:36: error: 'LIBUSB_LOG_LEVEL_INFO' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_INFO);
                                    ^
source/BridgeManager.cpp:519:36: error: 'LIBUSB_LOG_LEVEL_DEBUG' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_DEBUG);
                                    ^
source/BridgeManager.cpp: In member function 'int Heimdall::BridgeManager::Initialise(bool)':
source/BridgeManager.cpp:568:36: error: 'LIBUSB_LOG_LEVEL_NONE' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_NONE);
                                    ^
source/BridgeManager.cpp:572:36: error: 'LIBUSB_LOG_LEVEL_ERROR' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_ERROR);
                                    ^
source/BridgeManager.cpp:576:36: error: 'LIBUSB_LOG_LEVEL_WARNING' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_WARNING);
                                    ^
source/BridgeManager.cpp:580:36: error: 'LIBUSB_LOG_LEVEL_INFO' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_INFO);
                                    ^
source/BridgeManager.cpp:584:36: error: 'LIBUSB_LOG_LEVEL_DEBUG' was not declared in this scope
    libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_DEBUG);
                                    ^
source/BridgeManager.cpp: In member function 'void Heimdall::BridgeManager::SetUsbLogLevel(Heimdall::BridgeManager::UsbLogLevel)':
source/BridgeManager.cpp:1354:37: error: 'LIBUSB_LOG_LEVEL_NONE' was not declared in this scope
     libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_NONE);
                                     ^
source/BridgeManager.cpp:1358:37: error: 'LIBUSB_LOG_LEVEL_ERROR' was not declared in this scope
     libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_ERROR);
                                     ^
source/BridgeManager.cpp:1362:37: error: 'LIBUSB_LOG_LEVEL_WARNING' was not declared in this scope
     libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_WARNING);
                                     ^
source/BridgeManager.cpp:1366:37: error: 'LIBUSB_LOG_LEVEL_INFO' was not declared in this scope
     libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_INFO);
                                     ^
source/BridgeManager.cpp:1370:37: error: 'LIBUSB_LOG_LEVEL_DEBUG' was not declared in this scope
     libusb_set_debug(libusbContext, LIBUSB_LOG_LEVEL_DEBUG);
                                     ^
make[1]: *** [source/BridgeManager.o] Error 1
make[1]: Leaving directory `/home/frank/Downloads/Heimdall-master/heimdall'
make: *** [all] Error 2

**Comment by gcb** [comment]
i'm on the same boat as solartraveler. 

following those instructions btw. http://wiki.cyanogenmod.org/w/Install_and_compile_Heimdall
is there anything i can updated there to not require the local changes here?

**Comment by Benjamin-Dobell** [comment]
As the source of this issue is outdated dependencies (an old version of libusb-1.0), I'm closing this issue. The patch above need not be applied to your system libusb-1.0 files (if you're worried about messing with them), instead you can patch BridgeManager.cpp (or .h) to define the same enum.

However, these are work-arounds the best solution is to install a newer version of libusb-1.0 (either from your package manager or source).

**Comment by HeinrichHartmann** [comment]
Patch provided by @Solartraveler worked for me on Ubuntu 12.04. Thx.

**Comment by InfinitelyManic** [comment]
Ubuntu 12.04.5 LTS
# DEPS_CFLAGS = -I/usr/include/libusb-1.0
DEPS_CFLAGS = -I ../libusb-1.0/include
#works for me

**Comment by RobGroen** [comment]
My solution on a Ubuntu 12.04.5 LTS

edit the ./source/BridgeManager.cpp file
change this line
//#include <libusb.h>
to:
#include "../libusbx-1.0/include/libusb.h"

Edit Makefile
change the DEPS_CFLAGS to
DEPS_CFLAGS = -I ../libusbx-1.0/include
notice the space between "I" and "../'
