### ISSUE TITLE
Heimdall can't connect to GT-i9300 with android 4.3

### ISSUE THREAD

**Issue by anoteng** [Benjamin-Dobell/Heimdall#176]
I'm unable to connect to my GT-i9300 with the latest update from Samsung.
dmesg output:
[249607.300967] usb 2-1.2: new high-speed USB device number 6 using ehci-pci
[249607.395585] usb 2-1.2: New USB device found, idVendor=04e8, idProduct=685d
[249607.395592] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[249607.395595] usb 2-1.2: Product: Gadget Serial
[249607.395598] usb 2-1.2: Manufacturer: SAMSUNG
[249607.396086] cdc_acm 2-1.2:1.0: This device cannot do calls on its own. It is not a modem.
[249607.396166] cdc_acm 2-1.2:1.0: ttyACM0: USB ACM device

Heimdall output:
Heimdall v1.4.0

Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
      Manufacturer: "SAMSUNG"
           Product: "Gadget Serial"

            length: 18
      device class: 2
               S/N: 0
           VID:PID: 04E8:685D
         bcdDevice: 021B
   iMan:iProd:iSer: 1:2:0
          nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 83
           max packet size: 0010
          polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
           max packet size: 0200
          polling interval: 00
       endpoint[1].address: 02
           max packet size: 0200
          polling interval: 00
Claiming interface...
Setting up interface...

Initialising protocol...
ERROR: Failed to receive handshake response. Retrying...
ERROR: Failed to receive handshake response. Retrying...
ERROR: Failed to receive handshake response. Retrying...
ERROR: Failed to receive handshake response. Retrying...
ERROR: Failed to receive handshake response.
ERROR: Protocol initialisation failed!

Releasing device interface...

**Comment by Benjamin-Dobell** [comment]
Old issue. Presumably fixed now when master is compiled.
