### ISSUE TITLE
Can't get pit for Galaxy tab pro 8.4 - SM-T320

### ISSUE THREAD

**Issue by vikrant82** [Benjamin-Dobell/Heimdall#208]
Verbost logs from sudo heimdall print-pit --verbose --usb-log-level debug:

http://pastebin.com/4LbpQ9Cv

**Comment by luisfl** [comment]
Is this project alive? Dec 2015 and still not working...

**Comment by jipiboily** [comment]
Last commit in March, maybe, maybe not.

**Comment by JochenHoch2** [comment]
Hi there, 

just to let anone with a SM-T320 know: Current HEAD as of 29.3.16 works under Linux x86_64! Printing PIT, downloading PIT and flashing a new recovery all completed successfully. Either

- checkout the source and follow the instructions in Linux/README, Appendix B or
- wait for an official 1.4.2 release, which is in the works (Issue #295 ).

You will still get those
    WARNING: Empty bulk transfer after sending packet failed. Continuing anyway...
messages, but these can safely be ignored.

Personally, I'd say that this issue can be closed. Thanks for this cool tool!

**Comment by Benjamin-Dobell** [comment]
@JochenHoch2 Excellent! Thanks for letting me know.
