### ISSUE TITLE
How to manually generate a PIT file for Heimdall (GT-I5510)?

### ISSUE THREAD

**Issue by cookiengineer** [Benjamin-Dobell/Heimdall#213]
I bricked my phone with Odin, because it won't connect to the device. I tried out number 17 of OEM ROMs that work with my device and the given radio. No joke, I'm sitting here for over 18 hours now, it sucks that this device has no fastboot installed.

So what's the state?
- My phone is a Callisto (I5510GSMH from Poland (unbranded), I'm in Germany)
- I can not boot into anything else than recovery mod or the last flashed CWM variant installed from the stock recovery mod. This is falsely flashed to /system instead of /recovery and I don't know why.
- Softbricked, no bootable kernel.
- Power + T for stock recovery mod
- Power + E for Emergency DLoad Mode
- Power + Q for Downloading...(???) Mode is available
- I compiled omniarmv6 and tried to install it via adb sideload in the CWM 6.x variant, sideload worked - but failed at partition setup (file_contexts errors).

I can boot into CWM 6.0.3.7 or CWM 5.0.2.7, but none of both variants can flash an update.zip formatted file.

I have the proven correct stock ROM available (same variant from first boot before I bricked the phone), but it is in tar.md5 format. I extracted it and I have all the required files for recovery.img, amss etc. available.

I have no possibility to get Odin (3.09 or 4.34) working, both variants will get stuck at setup connection. Drivers correctly installed (tried out 7 different drivers), I know the KIES bug, I know the cable length bug etc. Not working in VM, not working on Win7, not working on WinXP, not working on Win7 _or_ WinXP of other computer. It's simply not working and a dead end. Seriously. Driver connects fine on Windows machines. My standard machine here is Ubuntu 14.04.

When trying to use Heimdall (my final choice after reading the whole dead link internet of the device) it gave me the typical interface error and I don't know what to do:

```
Initialising connection...
Detecting device...

        length: 18
      device class: 2
           S/N: 0
       VID:PID: 04E8:6601
     bcdDevice: 0100
   iMan:iProd:iSer: 1:2:0
      nb confs: 1

interface[0].altsetting[0]: num endpoints = 1
   Class.SubClass.Protocol: 02.02.01
       endpoint[0].address: 82
       max packet size: 0010
      polling interval: 09

interface[1].altsetting[0]: num endpoints = 2
   Class.SubClass.Protocol: 0A.00.00
       endpoint[0].address: 81
       max packet size: 0200
      polling interval: 00
       endpoint[1].address: 01
       max packet size: 0200
      polling interval: 00
Claiming interface...
Setting up interface...
libusbx: error [op_set_interface] setintf failed error -1 errno 71
ERROR: Setting up interface failed!
Releasing device interface...
```

Is there a way to setup a pit file manually? I have all the required partition image files laying around, but no access to a running kernel except the CWM on /system which can't flash anything.

My OS is Ubuntu 14.04, using heimdall-flash package (Heimdall v1.4.0).

**Comment by martensms** [comment]
Hey, I still got no reply. This still blocks me from using your awesome software :-(

**Comment by cookiengineer** [comment]
Closing this issue because it leads to nowhere.
