### ISSUE TITLE
Argument --<partition identifier> <filename> is not being correctly recognized

### ISSUE THREAD

**Issue by pcraposo** [Benjamin-Dobell/Heimdall#226]
OS: Ubuntu 14.04 LTS
Heimdall versions: 1.4.0 (Ubuntu Software Center), 1.4.1 (ppa.launchpad.net/modycz)
Phone: Samsung Galaxy Ace Plus (GT-S7500)

I have been trying to flash an unamed partition, available on the Stock image for this phone, and heimdall seems unable to recognize the partition is being specified by identifier, instead of by name.

$ sudo heimdall flash --resume --pit s7500.pit --5 partition.bin --no-reboot --verbose
Heimdall v1.4.1

Copyright (c) 2010-2014 Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

[STUFF DELETED]

ERROR: No partition with identifier "5" exists in the specified PIT.
Ending session...
Releasing device interface...

$

Also tried to create a Heimdall package, editing firmware.xml, and providing both the partition ID and partition file. Same error (Invalid ID).

**Comment by Benjamin-Dobell** [comment]
Closing as I think this may have been a user error i.e.

    ERROR: No partition with identifier "5" exists in the specified PIT.

Is only printed after "5" was successfully parsed into the integer ```5``` and a look-up based on that ID found no results in the corresponding PIT.
