### ISSUE TITLE
2 little mistakes

### ISSUE THREAD

**Issue by Ojigrande** [Benjamin-Dobell/Heimdall#232]
Hello.

The first error is on line 932 at the BridgeManager.cpp contains:
success = ReceivePacket(receiveFilePartPacket, receiveEmptyTransferFlags);
but it makes wrong timeout and lost flags.

I use this one:
success = ReceivePacket(receiveFilePartPacket, kDefaultTimeoutReceive, receiveEmptyTransferFlags);

The second error is on the line 747 at the same file:
if (ReceiveBulkTransfer(nullptr, 0, kDefaultTimeoutEmptyTransfer, false) < 0 && verbose)
That function doesn't receive packet. We have to set packet size at least 1 byte.

Kind Regards.

**Comment by Benjamin-Dobell** [comment]
Resolved some time ago.
