### ISSUE TITLE
32-bit heimdall fails on file >2G

### ISSUE THREAD

**Issue by ckiick** [Benjamin-Dobell/Heimdall#234]
> ls -l system.img.ext4
-rw-r--r-- 1 ckiick ckiick 2426084272 Feb 11  2014 system.img.ext4
> heimdall flash --SYSTEM system.img.ext4
ERROR: Failed to open file "system.img.ext4"
> file /usr/bin/heimdall
/usr/bin/heimdall: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=0x3fbac9bd4d709056f74fd795ebd3138a4ca52d39, stripped

Solution: compile using LFS support.
> git diff
diff --git a/heimdall/Makefile.am b/heimdall/Makefile.am
index e13860f..85435ac 100644
--- a/heimdall/Makefile.am
+++ b/heimdall/Makefile.am
@@ -1,6 +1,6 @@
 AUTOMAKE_OPTIONS = subdir-objects
 ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
-AM_CPPFLAGS = $(DEPS_CFLAGS) -std=c++0x -I../libpit/Source
+AM_CPPFLAGS = $(DEPS_CFLAGS) -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c+
 STATIC_LIBS = ../libpit/libpit-1.4.a
 bin_PROGRAMS = heimdall
 heimdall_SOURCES = source/Arguments.cpp \
diff --git a/heimdall/Makefile.in b/heimdall/Makefile.in
index bd12b77..6d0ce09 100644
--- a/heimdall/Makefile.in
+++ b/heimdall/Makefile.in
@@ -260,7 +260,7 @@ top_srcdir = @top_srcdir@
 udevadminstalled = @udevadminstalled@
 AUTOMAKE_OPTIONS = subdir-objects
 ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
-AM_CPPFLAGS = $(DEPS_CFLAGS) -std=c++0x -I../libpit/Source
+AM_CPPFLAGS = $(DEPS_CFLAGS) -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c+
 STATIC_LIBS = ../libpit/libpit-1.4.a
 heimdall_SOURCES = source/Arguments.cpp \
        source/BridgeManager.cpp \

**Comment by Benjamin-Dobell** [comment]
Closing as the new CMake build system enables large file support where possible.

**Comment by tomkagergely** [comment]
Hi,

A freshly cloned heimdall was not built by itself with largefile support, on a debian sid. I had to add the flags to CMakeLists.txt, so i assume that my system is capable to compile executables with largefile support. 
As the debian package was also without lfs, i sense some trouble here, but i am unable to debug. I am happy to help you in any way.

**Comment by Benjamin-Dobell** [comment]
The Debian package is *very* old, and was built before CMake was made the build system of choice. However, it would seem my CMake "script" is incorrect. If you're able to take a look at https://github.com/Benjamin-Dobell/Heimdall/blob/master/cmake/LargeFiles.cmake and work out what is failing that would be immensely appreciated.
