### ISSUE TITLE
Small bug prevents compiling in latest (linux) version, 1.4.1. Easily fixed!

### ISSUE THREAD

**Issue by u2n** [Benjamin-Dobell/Heimdall#235]
With output similar to bug 172, compilation stops.

A modified snippet from nohea's diff (in that thread, #172) corrects the problem.

In heimdall/source/BridgeManager.cpp:

  // libusb
  -#include \<libusb.h\>
  +#include "../../libusb-1.0/include/libusb.h"

For non-diff-speakers, edit the '#include' line under // libusb to remove \<libusb.h\> and insert "../../libusb-1.0/include/" in its place. The section should appear as:

// libusb
#include "../../libusb-1.0/include/libusb.h"

Posting new bug report since the methods in #172 do not work for v1.4.1 (indicating a difference).

**Comment by Benjamin-Dobell** [comment]
I'm closing this issue as the source of the problem is an out-dated install of libusb-1.0 on your system and not an issue with Heimdall. In your case your package manager is not providing an up-to-date libusb-1.0 version, so you must grab a newer version of libusb-1.0 for source and install it.
