### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by joshuatruscott** [Benjamin-Dobell/Heimdall#245]
Hi all, I'm not sure if I'm doing something wrong but every time I try to build heimdall-frontend in VS2012 I get these errors and warnings:

Warning	1	warning C4200: nonstandard extension used : zero-sized array in struct/union	C:\Users\Joshua\Downloads\Heimdall-issue-197\Heimdall-issue-197\libusb-1.0\include\libusb.h	740	1	heimdall
Warning	2	warning C4200: nonstandard extension used : zero-sized array in struct/union	C:\Users\Joshua\Downloads\Heimdall-issue-197\Heimdall-issue-197\libusb-1.0\include\libusb.h	771	1	heimdall
Warning	3	warning C4200: nonstandard extension used : zero-sized array in struct/union	C:\Users\Joshua\Downloads\Heimdall-issue-197\Heimdall-issue-197\libusb-1.0\include\libusb.h	1265	1	heimdall
Error	4	error C3861: 'valloc': identifier not found	C:\Users\Joshua\Downloads\Heimdall-issue-197\Heimdall-issue-197\heimdall\source\BridgeManager.cpp	952	1	heimdall
Error	5	error MSB6006: "cmd.exe" exited with code 3.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets	172	5	heimdall-frontend

Any help would be awesome! Thanks :)

**Comment by Benjamin-Dobell** [comment]
As Visual Studio is no longer a support build system, I'm closing this issue. Please follow the instructions in Win32/README.txt to build using MSYS2, MinGW-w64 and cmake.
