### ISSUE TITLE
Cannot load recovery

### ISSUE THREAD

**Issue by duke2106** [Benjamin-Dobell/Heimdall#260]
I'm trying to load the TWRP recovery image to my Tab Pro 10.1 (SM-T520) and Heimdall keeps stopping on 'initialising protocol'.

I was following the instructions on the cyanogenmod site.

This is on a Dell Latitude E6540 running Windows 7 64-bit.

Tablet is in download mode, and used zadig to get the USB driver properly loaded.

I also made sure my C++ redist package was installed.

The command I entered on the Command prompt was:

heimdall flash --RECOVERY recovery.img --no-reboot

Not sure what else you may need to assist, but I'm using Heimdall 1.4

**Comment by Benjamin-Dobell** [comment]
Closing as I believe this is resolved on master. Unfortunately there are no official packages yet so you'd need to compile it yourself.
