### ISSUE TITLE
Is Windows 7 64 supported?

### ISSUE THREAD

**Issue by bumbaras** [Benjamin-Dobell/Heimdall#265]
I'm asking, because I can't force Heimdall 1.3.1, 1.3.2 and 1.4.0 under W7 64 to work. Maybe there is no point on trying to repair sth what is not intended to work.
Typical results are:
ERROR: Failed to initialise protocol!
with WinUSB driver and Heimdall lower than 1.4.0. In 1.4.0 Heimdall hangs on "Initialise protocol".
After retrying action I get ERROR: Failed to receive device info response!

If driver is libusb-win32 or libusbK I get
ERROR: Failed to access device. libusb error: -12.
Heimdall 1.4.0 hangs on initialise protocol if libusbK is installed.

EDIT: tested on XP x86 and the results are the same. Either Heimdall doesn't like my Galaxy Y s5360, or driver installed by Kies is too new. Doesn't matter now, useless software to me.

**Comment by GTRsdk** [comment]
I had literally the same thing happen to me with my Galaxy S4 on Windows 7 64 bit

**Comment by Benjamin-Dobell** [comment]
#108
