### ISSUE TITLE
N7100 (Note II) listed as "Gadget Serial" insted of "Samsung Composite Device"

### ISSUE THREAD

**Issue by ionree** [Benjamin-Dobell/Heimdall#267]
This has nothing to do with Heimdall itself, but I think it would help a lot of people with their confusion when using Heimdall for the N7100 if you added this to the instructions/readme. When in download mode, windows lists the device as "Gadget Serial" instead of "Samsung Composite USB Device".
I dont know if this happens on all Note II devices though.
Also, there's a small typo on line 41 of the Windows README :laughing:

**Comment by djevertguzman** [comment]
it does not happen on the sprint note 2 or 4

**Comment by frank2019** [comment]
on  I9300  it  list as  "MSM8960"

**Comment by Benjamin-Dobell** [comment]
Yeah, unfortunately the devices say all sorts of garbage.

I'm closing this as there's not a "one size fits all" solution that I'm aware of.
