### ISSUE TITLE
Ubuntu 14.04 installer available?

### ISSUE THREAD

**Issue by BackEMF** [Benjamin-Dobell/Heimdall#279]
Is an Ubuntu 14.04 installer available or can the 13.04 version be used?
Asking this while 13.04 is no longer supported (ie, unable to install a library that heimdall needs, without jumping trough hoops)

Is heimdall still alive?  net most recent download is dated 2013-06-12.

**Comment by aPollO2k** [comment]
Last Installer worked for me under Linux Mint 17.2 (Ubuntu 14.04).

**Comment by BackEMF** [comment]
I'll try again. I just wanted to know if it works in 14.04 at al, so it does, so I will try harder..

Thanks.
