### ISSUE TITLE
SM-G130HN

### ISSUE THREAD

**Issue by blindvei** [Benjamin-Dobell/Heimdall#284]
Running 1.4.0 on Mac.
When download Pit this is reported:

Initialising connection...
Detecting device...
ERROR: Failed to detect compatible download-mode device.

What to do?

**Comment by Benjamin-Dobell** [comment]
Install:

https://bitbucket.org/benjamin_dobell/heimdall/downloads/Heimdall-1.4.1-Unofficial-Signed.dmg

**Comment by blindvei** [comment]
Device detected
:-)
