### ISSUE TITLE
i9300 "Protocol initialisation failed" @win7x64

### ISSUE THREAD

**Issue by Foxsa** [Benjamin-Dobell/Heimdall#298]
Im tryin to flash my phone but get:
>heimdall.exe flash --RECOVERY ..\cm-11-20150907-NIGHTLY-i9300-recovery.img --no-reboot
>Heimdall v1.4.0
>
>Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
>http://www.glassechidna.com.au/
>
>This software is provided free of charge. Copying and redistribution is
>encouraged.
>
>If you appreciate this software and you would like to support future
>development please consider donating:
>http://www.glassechidna.com.au/donate/
>
>Initialising connection...
>Detecting device...
>Claiming interface...
>Setting up interface...
>
>Initialising protocol...
>ERROR: Protocol initialisation failed!

>Releasing device interface...

Tryin to print PIT:

>heimdall print-pit --verbose
>Heimdall v1.4.0

>Copyright (c) 2010-2013, Benjamin Dobell, Glass Echidna
>http://www.glassechidna.com.au/

>This software is provided free of charge. Copying and redistribution is
>encouraged.

>If you appreciate this software and you would like to support future
>development please consider donating:
>http://www.glassechidna.com.au/donate/

>Initialising connection...
>Detecting device...
>      Manufacturer: "SAMSUNG"
>           Product: "Gadget Serial"
>
>            length: 18
>      device class: 2
>               S/N: 0
>           VID:PID: 04E8:685D
>         bcdDevice: 021B
>   iMan:iProd:iSer: 1:2:0
>          nb confs: 1
>
>interface[0].altsetting[0]: num endpoints = 1
>   Class.SubClass.Protocol: 02.02.01
>       endpoint[0].address: 83
>           max packet size: 0010
>          polling interval: 09
>
>interface[1].altsetting[0]: num endpoints = 2
>   Class.SubClass.Protocol: 0A.00.00
>       endpoint[0].address: 81
>           max packet size: 0200
>          polling interval: 00
>       endpoint[1].address: 02
>           max packet size: 0200
>          polling interval: 00
>Claiming interface...
>Setting up interface...
>
>Initialising protocol...
>ERROR: Failed to receive handshake response. Retrying...
>ERROR: Failed to receive handshake response. Retrying...
>ERROR: Failed to receive handshake response. Retrying...
>ERROR: Failed to receive handshake response. Retrying...
>ERROR: Failed to receive handshake response.
>ERROR: Protocol initialisation failed!
>
>Releasing device interface...

**Comment by Benjamin-Dobell** [comment]
Github is for development, please don't report issues unless you've verified the issue is still present on master. If it is, please details here and I'll reopen the issue.
