### ISSUE TITLE
OSX El Capitan Unsupported

### ISSUE THREAD

**Issue by weems** [Benjamin-Dobell/Heimdall#317]
Please expand the .dmg / .pkg to function on OSX 10.11.1 -- El Capitan. Thanks

**Comment by matgessel** [comment]
Duplicate of #291?

**Comment by kevinpapst** [comment]
Here is a shorthand version of the closed issue #291, try this file: 
https://bitbucket.org/benjamin_dobell/heimdall/downloads/Heimdall-1.4.1-Unofficial-Signed.dmg

**Comment by bunnyfu** [comment]
Kevinpapst, thanks a ton. Was also having problems building from source on OS X El Capitan.

**Comment by Silvercast** [comment]
thanks

**Comment by Benjamin-Dobell** [comment]
https://github.com/Benjamin-Dobell/Heimdall/issues/291
