### ISSUE TITLE
"This package is incompatible with this version of OS X and may fail to install."

### ISSUE THREAD

**Issue by mfn** [Benjamin-Dobell/Heimdall#336]
- Downloaded from https://bitbucket.org/benjamin_dobell/heimdall/downloads/heimdall-suite-1.4.0-mac.dmg .
- Opened dmg, opened pkg, got

> This package is incompatible with this version of OS X and may fail to install.
> Installing this package may damage your system, and the installation may fail. To stop the program and the installation, click “Cancel Installation”.
> [ ] Install Anyway  [ ] Cancel Installation

Tested on OS X El Capitan 10.11.4 (15E65)

**Comment by retorquere** [comment]
Same problem here.

**Comment by gfrancesco** [comment]
Same here, if you continue the installation actually fail.
Tried also to install with `brew`, no difference.

**Comment by leoshibata** [comment]
Same problem here.

**Comment by marekmaurizio** [comment]
Same.

**Comment by Benjamin-Dobell** [comment]
https://github.com/Benjamin-Dobell/Heimdall/issues/291

**Comment by SMN3110** [comment]
I have the same issues, what I need to do?
Thanks!

**Comment by socatres** [comment]
I just changed the instalation drive and it works

**Comment by jedisct1** [comment]
Same. I don't have multiple installation drives.

**Comment by benslamajihed** [comment]
Work on mac os 12.5

**Comment by lifeeric** [comment]
Tried both brew and dmg Same problem on 11.6
