### ISSUE TITLE
Heimdall not working in El Capitan

### ISSUE THREAD

**Issue by AgneevM** [Benjamin-Dobell/Heimdall#344]
Heimdall not installing properly and not recognized by Terminal (Screenshots attached)
<img width="614" alt="screen shot 2016-06-05 at 7 09 12 pm" src="https://cloud.githubusercontent.com/assets/19761269/15805775/4d83e56c-2b51-11e6-8db5-bf08bf2d1e67.png">
<img width="616" alt="screen shot 2016-06-05 at 7 09 25 pm" src="https://cloud.githubusercontent.com/assets/19761269/15805778/4ef943f6-2b51-11e6-8ec6-b3c3dc1686c5.png">
<img width="289" alt="screen shot 2016-06-05 at 7 09 35 pm" src="https://cloud.githubusercontent.com/assets/19761269/15805776/4e155984-2b51-11e6-8f1b-dd79b7d8b94a.png">
<img width="393" alt="screen shot 2016-06-05 at 7 09 57 pm" src="https://cloud.githubusercontent.com/assets/19761269/15805777/4ec7a6c0-2b51-11e6-8e01-56e25d50ece7.png">

**Comment by callumgare** [comment]
Yeah, definitly still an issue. Here's a possible work around though: https://github.com/Benjamin-Dobell/Heimdall/issues/291

**Comment by Benjamin-Dobell** [comment]
Closed as there's an existing issue, and solution (linked above).

**Comment by AgneevM** [comment]
I appreciate the prompt reply.
