### ISSUE TITLE
macOS 10.12 installer fail

### ISSUE THREAD

**Issue by cederom** [Benjamin-Dobell/Heimdall#366]
Hello,
The official Heimdall installer for macOS [1] does not install properly on 10.12.
Best regards,
Tomek

[1] https://bitbucket.org/benjamin_dobell/heimdall/downloads/heimdall-suite-1.4.0-mac.dmg

**Comment by Benjamin-Dobell** [comment]
Please look for similar issues before opening new ones, this has a;ready been addressed on Github (numerous times):
https://github.com/Benjamin-Dobell/Heimdall/issues/291

**Comment by cederom** [comment]
True :-) Sorry :-)
