### ISSUE TITLE
Building master fails on osx 10.12.1

### ISSUE THREAD

**Issue by vigbk** [Benjamin-Dobell/Heimdall#383]
clang: error: no such file or directory: '1'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
depbase=`echo source/Arguments.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	/usr/bin/clang++ -DHAVE_CONFIG_H -I.  1 -std=c++0x -I../libpit/Source   -g -O2 -MT source/Arguments.o -MD -MP -MF $depbase.Tpo -c -o source/Arguments.o source/Arguments.cpp &&\
	mv -f $depbase.Tpo $depbase.Po
clang: error: no such file or directory: '1'
make[1]: *** [source/Arguments.o] Error 1
make: *** [all] Error 2

**Comment by Benjamin-Dobell** [comment]
I'm going to close this for now macOS has been my primary OS for years and I've regularly built Heimdall without issue, including on 10.12.x.

I'm not sure what's going on with all the references to `'1'`, however I'm guessing it was an issue with your particular setup. If you've followed the README exactly and this is an on-going problem, then please provide some more information about the steps you've followed, relevant software versions etc.
