### ISSUE TITLE
heimdall-frontend is missing HIDDEN and MOVINAND partitions

### ISSUE THREAD

**Issue by memartinb** [Benjamin-Dobell/Heimdall#39]
Users are unable to flash Gingerbread ROMs to Samsung devices (e.g. a GT-P1000) using heimdall-frontend because partition entries for the --hidden (hidden.rfs) and --movinand (movinand.mst) CLI options cannot be added via the GUI.

Tested with heimdall-frontend v1.3.2 on both Ubuntu 11.10 Oneiric and 12.04 Precise.

**Comment by xsrf** [comment]
Hi, I can confirm this issue. My pit file (extracted by heimdall) shows a HIDDEN partition but I'm not able to choose it in heimdall frontend for flashing. Same for MOVINAND (which I don't need). Also, Partition "IBL+PBL" shows up twice in the drop down but only once in the pit. I can even assign two different bin-files for "IBL+PBL" this way. May this be related?
