### ISSUE TITLE
Firmware Backup/Dump

### ISSUE THREAD

**Issue by hy-l** [Benjamin-Dobell/Heimdall#402]
hi, all
can I use heimdall to dump the current firmware on the phone to a file? ( e.g. /system, /efs, /data, etc. ) 
at this point, i just want to see what inside the /efs from bootloader, and make a backup  without rooting the device. Is it possible? How?
If heimdall dose not have the backup feature, could you please add this in the future?

thanks. :)

**Comment by Benjamin-Dobell** [comment]
It's not possible unfortunately - although for security reasons I'm somewhat thankful.

Heimdall did at one point have _theoretical_ support for dumping firmware, however no publicly available phones actually supported the feature. Heimdall communicates with Loke software running on the device, so Heimdall can only support what Loke supports - all publicly released versions of Loke (that I've investigated) do not support this feature.

**Comment by hy-l** [comment]
okay, maybe the only way is rooting my phone.
also, i never expect to get an answer so fast. thank you. ;)
