### ISSUE TITLE
Support for downloading images?

### ISSUE THREAD

**Issue by Hypexed** [Benjamin-Dobell/Heimdall#424]
Hello. Yes this an issue I have and not with the code. But I can't see how to post a feature request.

Anyway. What is the chance of supporting image downloading? It can get a PIT but that's about it. :-)

I looked though the code but it wasn't obvious how to download data or even if it is possible.  I understand the point of Heimdall is to flash firmware. It would be useful to back up firmware images and partitions. I don't know if Loke even allows to read more than the PIT.

**Comment by Benjamin-Dobell** [comment]
Please refer to https://github.com/Benjamin-Dobell/Heimdall/issues/97

**Comment by Hypexed** [comment]
Thanks.  I thought this may be the case.
