### ISSUE TITLE
links need to be updated on xda

### ISSUE THREAD

**Issue by botmtl** [Benjamin-Dobell/Heimdall#436]
links need to be edited on xda (ref:https://forum.xda-developers.com/showthread.php?t=755265)
(sorry can't even post a reply to the real links on xda because I don't have the required 10 posts...)

**Comment by Benjamin-Dobell** [comment]
@botmtl Thanks for the heads up. I must have accidentally deleted our Amazon S3 redirect rules.

Rather than just update those URLs on XDA, I'm redirecting `/products/*` to `/*`, because other website also have old links and I don't want to break anyones links 😄
