### ISSUE TITLE
Call quality

### ISSUE THREAD

**Issue by Jackhford** [Benjamin-Dobell/Heimdall#451]
I have a T-mobile Galaxy Note 4 N910T (trltetmo) and LOS 14.1 but I'm having big calling problems. Calls start fine, then start to garble, and then drop. Can anyone help me with this?
Thanks

**Comment by Benjamin-Dobell** [comment]
We are not affiliated with LineageOS (or any ROMs, official or otherwise) please try someone from LineageOS and/or a warranty claim.
