### ISSUE TITLE
How to compile for Raspi Pi 3b

### ISSUE THREAD

**Issue by AxelRingwald** [Benjamin-Dobell/Heimdall#471]
Hi Benajmin,

I tried to compile the Heimdall-project on my Raspi Pi 3 b. It failled with error.
Is it possible to give a short instruction how to compile the project on a Raspi.

Notice: I'm a beginner in Linux.

Tks
Axel

**Comment by Benjamin-Dobell** [comment]
Raspberry Pi isn't an officially supported platform, so I'm going to close this. However, I would think that as long as you have CMake and libusb installed you shouldn't run into any major issues.

Just follow the compilation instructions in the Linux README, but when you run CMake run it like:

```
cmake -DDISABLE_FRONTEND=ON -DDCMAKE_BUILD_TYPE=Release ..
```

Setting `DISABLE_FRONTEND` to `ON` will just build Heimdall (CLI) and not the Heimdall Frontend (GUI).
