### ISSUE TITLE
SM-P605 cannot flash TWRP recovery.

### ISSUE THREAD

**Issue by parsanoori** [Benjamin-Dobell/Heimdall#492]
I'm on archlinux with a SM-P605 device.
On bootloader mode when I run `sudo heimdall flash --RECOVERY twrp-3.1.1-0-lt03ltexx.img.tar`:
```
Heimdall v1.4.2

Copyright (c) 2010-2017 Benjamin Dobell, Glass Echidna
http://www.glassechidna.com.au/

This software is provided free of charge. Copying and redistribution is
encouraged.

If you appreciate this software and you would like to support future
development please consider donating:
http://www.glassechidna.com.au/donate/

Initialising connection...
Detecting device...
Claiming interface...
Setting up interface...

Initialising protocol...
Protocol initialisation successful.

Beginning session...

Some devices may take up to 2 minutes to respond.
Please be patient!

Session begun.

Downloading device's PIT file...
PIT file download successful.

Uploading RECOVERY
100%
ERROR: Failed to confirm end of file transfer sequence!
ERROR: RECOVERY upload failed!

Ending session...
Releasing device interface...
```

I've got several TWRP images from [official ones](https://dl.twrp.me/lt03ltexx/twrp-3.1.1-0-lt03ltexx.img.tar.html) and [unofficial ones](https://forum.xda-developers.com/t/recovery-sm-p605-unofficial-twrp-3-5-1-for-lt03lte-18-03-2021.3635803/).

When I boot to recovery mode I see that the stock recovery is there.
What's the problem ?

**Comment by nickelc** [comment]
You have to unpack the tarball and use the `recovery.img` file as the argument.
And don't forget to boot the recovery first after flashing because the stock image will probably restore the recovery partition.

**Comment by parsanoori** [comment]
Yes, made a big mistake.
