### ISSUE TITLE
kind plea from visually impaired Samsung Galaxy Chat (B5330) user

### ISSUE THREAD

**Issue by JanuszChmiel** [Benjamin-Dobell/Heimdall#493]
Dear specialist,
Thanks to powerful New Kingroot rooting tool, which have contained special tool to send my phone number to thirt parties, so special numbers from Hungaria have started to randomly call Me, I have been so strongly afraid because of my strange phone behaviour, that I have applied The factory reset. Unfortunately, I have removed Dstr Touchwiz Samsung Launcher. And I have also removed Samsung TTS and GOogle TTS by using this rooting tool. After factory reset, my phone is unusable, because Talkback can not speak and I can not install some launcher such as Kiss Launcher, because I can not enable USB debug mode.
Do you think, that somebody have created package for yours flashing tool for Samsung Galaxy Chat (B5330) for Czech Republic?
Unfortunately, I do not know, how to overcome my issues, which I have prepared for myselves because of my experiments. Fortunately, Android kernel work and New kingroot have some kernel tweaks settings. I could even unroot my phone by using Drfone, but if I can not enable USB fdebugging, I Am helpless. Fortunately, I have found AN solution. Samsung Galaxy Chat (B5330)  contain special button, which can be assign to execute one of preinstalled apps including settings. Thanks to this button, I can start settings after factory reset. But phone is very unstable. After restart, phone stuck at The Samsung logo. And unfortunately, even wipe cache partition available inside Android Recovery. Sure, There is also special item apply update by using ADB. But in this mode, adb shell will very probably not work. And I Am afraid, that in this mode, processes inside phone will wait for flashboot and not for adb shell command or for An commandwhich will install  some .apk package such as Kiss launcher.
Thank you for yours advice how to flash this phone
Samsung Galaxy Chat (B5330

**Comment by Benjamin-Dobell** [comment]
Please try a forum such as XDA.

As far as Heimdall is concerned. I doubt the model of phone you've mentioned is supported by Heimdall. Generally only Galaxy/Note series devices are supported.
